android: remove test_mappings
When building with a recent bazel_common_rules repo, we see:

    ERROR: error loading package 'imgtech-module': Every .bzl file must have
    a corresponding package, but '//build/bazel_common_rules/test_mappings:test_mappings.bzl'
    does not have one.
    Please create a BUILD file in the same or any parent directory.
    Note that this BUILD file does not need to do anything except exist.

The test_mappings macro has been deprecated in [1] and removed in [2].

Remove it here as well to solve the build error.

[1] https://android-review.googlesource.com/c/platform/build/bazel_common_rules/+/3015394
[2] https://android-review.googlesource.com/c/platform/build/bazel_common_rules/+/3025075
Signed-off-by: Mattijs Korpershoek <mkorpershoek@baylibre.com>