am62/am62p: add missing definitions for 23.3
When building, we have the following errors:

error: use of undeclared identifier 'RGX_DRIVER_DEFAULT_TIME_SLICES_SUM'
static_assert(RGX_DRIVER_DEFAULT_TIME_SLICES_SUM <= PVRSRV_VZ_TIME_SLICE_MAX

Fix them by adding all missing defines in config_kernel_am62{,p}_android.h

Signed-off-by: Mattijs Korpershoek <mkorpershoek@baylibre.com>